---
  - name: install meteor
    become: yes
    become_method: sudo
    script: /Users/jkennemer/Projects/PyNetUDev/ansible/roles/meteor/files/meteor.sh

  - name: install meteor npm modules
    become: yes
    become_method: sudo
    npm: name={{ item }} global=yes state=present
    with_items:
      - meteorite
      - forever
