---

nginx_env:
 RUNLEVEL: 1

nginx_installation_types_using_service: ["packages", "configuration-only"]

nginx_is_el: "{{ ansible_distribution in ['RedHat', 'CentOS'] }}"

# The user to run nginx
nginx_user: "www-data"

# A list of directives for the events section.
nginx_events_params:
  - worker_connections 512

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
 default:
     - listen 80
     - server_name _
     - root "/usr/share/nginx/html"
     - index index.html
# A list of hashs that define additional configuration
nginx_configs:
#  proxy:
#      - proxy_set_header X-Real-IP  $remote_addr
#      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
#  upstream:
#      - upstream foo { server 127.0.0.1:8080 weight=10; }
  geo:
      - geo $local {
          default 0;
          127.0.0.1 1;
        }
  gzip:
      - gzip on
      - gzip_disable msie6

# A list of hashs that define uer/password files
# nginx_auth_basic_files:
#   demo:
#     - foo:$apr1$mEJqnFmy$zioG2q1iDWvRxbHuNepIh0 # foo:demo , generated by : htpasswd -nb foo demo
