---
- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    site_name: "nvsdb"
    site_directory: "/var/www"

  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'bash', tags: 'bash' }
    - { role: 'virtualenv', 'virtualenv' }
    - { role: 'python3', 'python3' }
#    - { role: 'nginx', 'nginx'}
    - { role: 'Django', 'Django'}
