---
- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo

  roles:
    - { role: 'common', tags: 'common' }
    - { role: 'bash', tags: 'bash' }
    - { role: 'virtualenv', 'virtualenv' }
    - { role: 'python3', 'python3' }
#    - { role: 'nginx', 'nginx'}
#    - { role: 'postgresql', 'postgresql'}
    - { role: 'Stouts.mongodb', 'Stouts.mongodb' }
    - { role: 'Django', 'Django'}
    - { role: 'nodejs', 'nodejs' }
    - { role: 'meteor', 'meteor' }
