---

mongodb_enabled: yes
mongodb_package: mongodb-org
mongodb_user: mongodb
mongodb_daemon_name: "{{ 'mongod' if ('mongodb-org' == mongodb_package) else 'mongodb' }}"
# mongodb_daemon_name: mongodb
mongodb_conf_port: 27017
mongodb_conf_httpinterface: no

# Log rotation
mongodb_logrotate: yes                             # Rotate mongodb logs.
mongodb_logrotate_options:
  - compress
  - copytruncate
  - daily
  - dateext
  - rotate 7
  - size 10M
